export type Topic = { slug: string; name: string; description: string; icon: string };
export type Article = { slug: string; topic: string; topicSlug: string; title: string; summary: string; publishedAt: string; updatedAt: string; body: string[]; sources: { label: string; href: string }[] };

export const topics: Topic[] = [
  { slug: 'menopause', name: '갱년기 이해하기', description: '몸의 변화와 치료 선택지를 차분히 살펴봅니다.', icon: '◐' },
  { slug: 'sleep-mood', name: '잠과 마음', description: '수면, 기분, 스트레스의 연결을 이해합니다.', icon: '☾' },
  { slug: 'bone-muscle', name: '뼈와 근육', description: '오래 움직이기 위한 생활 습관을 찾습니다.', icon: '⌁' },
  { slug: 'everyday-care', name: '일상 건강', description: '검진과 식사, 활동을 생활에 맞게 정리합니다.', icon: '✳' },
];

export const articles: Article[] = [
  { slug: 'menopause-when-to-see-a-doctor', topic: '갱년기 이해하기', topicSlug: 'menopause', title: '갱년기 증상, 언제 진료 상담을 시작하면 좋을까요?', summary: '참는 것이 답인지 헷갈릴 때 살펴볼 신호와 진료 준비 방법입니다.', publishedAt: '2026-08-11', updatedAt: '2026-08-11', body: ['갱년기는 마지막 월경 전후의 전환기를 말하며, 안면홍조·야간 발한·수면 변화·기분 변화처럼 사람마다 다른 증상이 나타날 수 있습니다. 증상이 있다는 사실만으로 위험하다는 뜻은 아니지만, 생활에 영향을 준다면 상담할 이유가 충분합니다.', '특히 월경이 끝난 뒤 다시 출혈이 있거나, 출혈 양상이 갑자기 달라졌다면 갱년기라고 단정하지 말고 진료를 받아야 합니다. 심한 두근거림, 흉통, 호흡 곤란, 갑작스러운 신경학적 증상도 즉시 평가가 필요한 신호입니다.', '진료 전에는 증상이 언제 시작됐는지, 잠·기분·일상에 어떤 영향을 주는지, 복용 중인 약과 가족력을 간단히 적어 보세요. 기록은 정답을 찾기 위한 시험지가 아니라 의료진과 대화를 시작하는 지도입니다.'], sources: [{ label: 'NHS: Menopause', href: 'https://www.nhs.uk/conditions/menopause/' }, { label: 'NAMS: MenoNote (symptoms)', href: 'https://menopause.org/patient-education/menonotes' }] },
  { slug: 'hot-flash-daily-record', topic: '갱년기 이해하기', topicSlug: 'menopause', title: '열감과 땀, 내 패턴을 알아차리는 7일 기록', summary: '증상을 없애기 전, 먼저 내 생활과의 관계를 알아보는 방법입니다.', publishedAt: '2026-08-08', updatedAt: '2026-08-11', body: ['열감과 야간 발한은 갱년기에 흔히 이야기되는 혈관운동 증상입니다. 강도와 빈도는 매우 다양하며, 잠이나 업무, 외출에 미치는 영향도 서로 다릅니다.', '7일 동안 날짜, 시간, 느낀 강도, 그 직전의 활동과 음식·음료, 수면 상태를 짧게 기록해 보세요. 특정 음식이나 스트레스가 모두에게 원인이 되는 것은 아니지만, 내 패턴을 발견하는 데 도움이 될 수 있습니다.', '기록을 보며 생활 조절만으로 충분한지, 상담이 필요한지 판단할 실마리를 얻을 수 있습니다. 증상이 괴롭거나 갑자기 심해졌다면 기록을 들고 의료진과 상의하세요.'], sources: [{ label: 'NHS: Hot flushes and night sweats', href: 'https://www.nhs.uk/conditions/menopause/symptoms/' }, { label: 'NHS: Menopause treatment', href: 'https://www.nhs.uk/conditions/menopause/treatment/' }] },
  { slug: 'sleep-after-45', topic: '잠과 마음', topicSlug: 'sleep-mood', title: '자꾸 깨는 밤, 수면의 질부터 살펴보세요', summary: '갱년기 전후 잠이 달라졌을 때 확인할 생활 신호를 정리합니다.', publishedAt: '2026-08-05', updatedAt: '2026-08-05', body: ['수면은 나이가 들수록 한 번에 이어지는 방식이 달라질 수 있고, 갱년기 전후의 야간 발한이나 기분 변화가 잠을 방해하기도 합니다. 피곤하다고 해서 반드시 갱년기 때문이라고 볼 수는 없습니다.', '취침·기상 시간을 가능한 한 일정하게 하고, 낮 시간의 가벼운 활동과 아침 빛 노출을 생활에 넣어 보세요. 잠들기 직전의 음주나 과도한 카페인은 수면을 더 잘게 만들 수 있습니다.', '코골이와 숨 멎음, 다리 불편감, 지속되는 우울감 또는 낮의 심한 졸림이 있다면 다른 수면 문제도 함께 평가받는 것이 좋습니다.'], sources: [{ label: 'NHLBI: Healthy Sleep Habits', href: 'https://www.nhlbi.nih.gov/health/sleep-deprivation/healthy-sleep-habits' }, { label: 'NHS: Menopause symptoms', href: 'https://www.nhs.uk/conditions/menopause/symptoms/' }] },
  { slug: 'bone-health-small-steps', topic: '뼈와 근육', topicSlug: 'bone-muscle', title: '뼈 건강은 ‘한 번에 많이’보다 ‘꾸준히 움직이기’에서 시작됩니다', summary: '골밀도 검사를 포함해 오래 움직이기 위한 기본 질문을 정리합니다.', publishedAt: '2026-08-02', updatedAt: '2026-08-11', body: ['폐경 후에는 에스트로겐 변화와 함께 골 손실 속도가 달라질 수 있습니다. 하지만 뼈 건강은 한 가지 음식이나 운동만으로 결정되지 않으며, 나이·체중·골절 경험·약물·가족력 등 여러 요소를 함께 봅니다.', '걷기처럼 체중을 싣는 활동과 근육을 쓰는 운동은 일상 기능을 지키는 데 도움이 됩니다. 시작 전 관절 통증, 낙상 경험, 기존 질환이 있다면 자신의 상태에 맞는 운동을 상담하세요.', '골절을 겪었거나 키가 줄고 등이 굽는 변화가 느껴진다면 검사를 포함해 의료진에게 골 건강 평가가 필요한지 물어보세요.'], sources: [{ label: 'ACOG: Osteoporosis', href: 'https://www.acog.org/womens-health/faqs/osteoporosis' }, { label: 'WHO: Physical activity', href: 'https://www.who.int/news-room/fact-sheets/detail/physical-activity' }] },
  { slug: 'health-checkup-questions', topic: '일상 건강', topicSlug: 'everyday-care', title: '건강검진 결과를 받았을 때, 먼저 물어볼 세 가지', summary: '수치 하나에 흔들리지 않고 다음 행동을 정하는 질문들입니다.', publishedAt: '2026-07-30', updatedAt: '2026-07-30', body: ['검진 결과의 숫자는 현재 상태를 살펴보는 하나의 단서입니다. 결과지를 받았을 때는 기준 범위를 벗어났는지뿐 아니라, 내 나이와 병력에서 그 수치가 무엇을 의미하는지 확인하는 과정이 중요합니다.', '“재검이 필요한가요?”, “생활에서 바꿀 수 있는 한 가지는 무엇인가요?”, “다음 확인 시점은 언제인가요?”처럼 구체적인 질문을 적어 두세요. 수치 해석과 치료 결정은 개인의 상태에 따라 달라집니다.', '검진은 불안을 위한 성적표가 아니라 예방과 상담을 위한 출발점입니다. 증상이 있거나 걱정되는 가족력이 있다면 검진 시기와 별개로 진료를 받으세요.'], sources: [{ label: 'WHO: Health promotion', href: 'https://www.who.int/health-topics/health-promotion' }, { label: '질병관리청 국가건강정보포털', href: 'https://health.kdca.go.kr/' }] },
  { slug: 'national-screening-checklist-2026', topic: '일상 건강', topicSlug: 'everyday-care', title: '2026년 국가건강검진, 대상 여부부터 확인하는 방법', summary: '검진표를 받았을 때 내게 해당하는 항목과 결과 확인의 다음 단계를 정리합니다.', publishedAt: '2026-08-11', updatedAt: '2026-08-11', body: ['국가건강검진은 질병을 조기에 발견하고 예방하기 위한 검사입니다. 대상 여부와 검진 항목은 연령, 성별, 가입 유형 등에 따라 달라질 수 있으므로, 안내문만 보고 추측하기보다 국민건강보험공단의 조회 서비스에서 올해 대상인지 확인하는 것이 가장 정확합니다.', '질병관리청 국가건강정보포털은 일반건강검진이 보통 2년 주기로 운영되며, 성별·연령별 항목이 다를 수 있다고 안내합니다. 예를 들어 여성의 골밀도 검사는 정해진 연령에 실시될 수 있고, 개인의 병력이나 증상이 있다면 국가검진 일정과 별개로 진료 상담이 필요할 수 있습니다.', '검진 전에는 예약 기관의 준비 안내를 확인하고, 검진 뒤에는 결과지의 재검·상담 권고를 놓치지 마세요. 검진은 모든 질병을 찾아내거나 안전을 보장하는 검사가 아니므로, 새롭거나 지속되는 증상은 결과와 무관하게 의료진과 상의해야 합니다.'], sources: [{ label: '질병관리청 국가건강정보포털: 건강검진(국가건강검진)', href: 'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=6671' }, { label: '질병관리청: 국가건강검진 기준 및 질 관리', href: 'https://www.kdca.go.kr/kdca/3360/subview.do' }, { label: '국민건강보험공단', href: 'https://www.nhis.or.kr/' }] },
];

export function getArticle(slug: string) { return articles.find((article) => article.slug === slug); }
export function getTopic(slug: string) { return topics.find((topic) => topic.slug === slug); }
