import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { Disclaimer } from '../../../components/disclaimer';
import { SiteFooter } from '../../../components/site-footer';
import { SiteHeader } from '../../../components/site-header';
import { articles, getArticle } from '../../../content/editorial';
type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return articles.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const article = getArticle((await params).slug); if (!article) return {}; return { title: article.title, description: article.summary, alternates: { canonical: `/article/${article.slug}` }, openGraph: { title: article.title, description: article.summary, type: 'article', publishedTime: article.publishedAt, modifiedTime: article.updatedAt } }; }
export default async function ArticlePage({ params }: Props) { const article = getArticle((await params).slug); if (!article) notFound(); const jsonLd = { '@context': 'https://schema.org', '@type': 'Article', headline: article.title, description: article.summary, datePublished: article.publishedAt, dateModified: article.updatedAt, inLanguage: 'ko-KR', mainEntityOfPage: `https://wonon.ehon365.kr/article/${article.slug}`, publisher: { '@type': 'Organization', name: '원온', url: 'https://wonon.ehon365.kr' } }; return <><SiteHeader /><main id="main-content" className="article-layout"><article><p className="article-topic">{article.topic}</p><h1>{article.title}</h1><p className="article-deck">{article.summary}</p><p className="article-meta"><time dateTime={article.publishedAt}>발행 {article.publishedAt}</time> · <time dateTime={article.updatedAt}>수정 {article.updatedAt}</time></p><div className="article-body">{article.body.map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div><aside className="source-box"><h2>이 글을 확인한 자료</h2><ul>{article.sources.map((source) => <li key={source.href}><a href={source.href} target="_blank" rel="noreferrer">{source.label}</a></li>)}</ul></aside></article><Disclaimer /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></main><SiteFooter /></>; }
